public enum S_InputTypes
{
    MENU_BUTTON,

    RIGHT_PRIMARY_BUTTON_PRESS,
    RIGHT_PRIMARY_BUTTON_RELEASE,
    RIGHT_PRIMARY_BUTTON_TOUCH,
    RIGHT_PRIMARY_BUTTON_UNTOUCH,

    RIGHT_SECONDARY_BUTTON_PRESS,
    RIGHT_SECONDARY_BUTTON_RELEASE,
    RIGHT_SECONDARY_BUTTON_TOUCH,
    RIGHT_SECONDARY_BUTTON_UNTOUCH,

    LEFT_PRIMARY_BUTTON_PRESS,
    LEFT_PRIMARY_BUTTON_RELEASE,
    LEFT_PRIMARY_BUTTON_TOUCH,
    LEFT_PRIMARY_BUTTON_UNTOUCH,

    LEFT_SECONDARY_BUTTON_PRESS,
    LEFT_SECONDARY_BUTTON_RELEASE,
    LEFT_SECONDARY_BUTTON_TOUCH,
    LEFT_SECONDARY_BUTTON_UNTOUCH,

    LEFT_TRIGGER_BUTTON_PRESS,
    LEFT_TRIGGER_BUTTON_RELEASE,

    RIGHT_TRIGGER_BUTTON_PRESS,
    RIGHT_TRIGGER_BUTTON_RELEASE,

    LEFT_GRIP_BUTTON_PRESS,
    LEFT_GRIP_BUTTON_RELEASE,

    RIGHT_GRIP_BUTTON_PRESS,
    RIGHT_GRIP_BUTTON_RELEASE,

    LEFT_PRIMARY_2D_AXIS,
    LEFT_PRIMARY_2D_AXIS_RELEASE,
    LEFT_PRIMARY_2D_AXIS_BUTTON_PRESS,
    LEFT_PRIMARY_2D_AXIS_BUTTON_RELEASE,
    LEFT_PRIMARY_2D_AXIS_TOUCH,
    LEFT_PRIMARY_2D_AXIS_UNTOUCH,
    LEFT_PRIMARY_2D_AXIS_LEFT_TILT,
    LEFT_PRIMARY_2D_AXIS_RIGHT_TILT,
    LEFT_PRIMARY_2D_AXIS_UP_TILT,
    LEFT_PRIMARY_2D_AXIS_DOWN_TILT,
    LEFT_PRIMARY_2D_AXIS_LEFT_TILT_RELEASE,
    LEFT_PRIMARY_2D_AXIS_RIGHT_TILT_RELEASE,
    LEFT_PRIMARY_2D_AXIS_UP_TILT_RELEASE,
    LEFT_PRIMARY_2D_AXIS_DOWN_TILT_RELEASE,

    RIGHT_PRIMARY_2D_AXIS,
    RIGHT_PRIMARY_2D_AXIS_RELEASE,
    RIGHT_PRIMARY_2D_AXIS_BUTTON_PRESS,
    RIGHT_PRIMARY_2D_AXIS_BUTTON_RELEASE,
    RIGHT_PRIMARY_2D_AXIS_TOUCH,
    RIGHT_PRIMARY_2D_AXIS_UNTOUCH,
    RIGHT_PRIMARY_2D_AXIS_LEFT_TILT,
    RIGHT_PRIMARY_2D_AXIS_RIGHT_TILT,
    RIGHT_PRIMARY_2D_AXIS_UP_TILT,
    RIGHT_PRIMARY_2D_AXIS_DOWN_TILT,
    RIGHT_PRIMARY_2D_AXIS_LEFT_TILT_RELEASE,
    RIGHT_PRIMARY_2D_AXIS_RIGHT_TILT_RELEASE,
    RIGHT_PRIMARY_2D_AXIS_UP_TILT_RELEASE,
    RIGHT_PRIMARY_2D_AXIS_DOWN_TILT_RELEASE,

    NONE,
}