public enum S_OculusInputTypes
{
    LeftJoystickPress,
    LeftJoystickNorth,
    LeftJoystickSouth,
    LeftJoystickWest,
    LeftJoystickEast,
    LeftJoystickRelease,
    LeftJoystickNorthRelease,
    LeftJoystickSouthRelease,
    LeftJoystickWestRelease,
    LeftJoystickEastRelease,
    LeftJoystickTouch,
    LeftJoystickIndexTriggerPress,
    LeftJoystickIndexTriggerRelease,
    LeftJoystickHandTriggerPress,
    LeftJoystickHandTriggerRelease,


    RightJoystickPress,
    RightJoystickNorth,
    RightJoystickSouth,
    RightJoystickWest,
    RightJoystickEast,
    RightJoystickRelease,
    RightJoystickNorthRelease,
    RightJoystickSouthRelease,
    RightJoystickWestRelease,
    RightJoystickEastRelease,
    RightJoystickTouch,
    RightJoystickIndexTriggerPress,
    RightJoystickIndexTriggerRelease,
    RightJoystickHandTriggerPress,
    RightJoystickHandTriggerRelease,


    AButtonPress,
    BButtonPress,
    XButtonPress,
    YButtonPress,

    AButtonRelease,
    BButtonRelease,
    XButtonRelease,
    YButtonRelease,

    AButtonTouch,
    BButtonTouch,
    XButtonTouch,
    YButtonTouch,
    LeftIndexTouch,
    LeftThumbrestTouch,
    RightIndexTouch,
    RightThumbrestTouch,
    AButtonUntouch,
    BButtonUntouch,
    XButtonUntouch,
    YButtonUntouch,
    LeftIndexUntouch,
    LeftThumbrestUntouch,
    LeftJoystickUntouch,
    RightJoystickUntouch,
    RightIndexUntouch,
    RightThumbrestUntouch,

    StartButtonPress
}
